### ISSUE TITLE
Only tab focus to form input elements

### ISSUE THREAD

**Issue by donovan-graham** [NV/flying-focus#1]
Awesome effect, but I'd like to know how to limit this to only work on form input elements. Is there some way to do this?

**Comment by NV** [comment]
You mean exclude links and elements with tabIndex, is that correct? Why?

**Comment by donovan-graham** [comment]
Yes, that's right. I would use this on forms to help guide a user from a
user experience standpoint. Whilst tabbing onto links is a bit strange
especially those links that have been styled for other purposes, like
drop-down (fly-out) menu systems. If there is someway to control the
elements that are affected in a config/setup that would provide flexibility
for different uses.

On Fri, Sep 20, 2013 at 3:07 PM, Nikita Vasilyev
notifications@github.comwrote:

> You mean exclude links and elements with tabIndex, is that correct? Why?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NV/flying-focus/issues/1#issuecomment-24808855
> .

## 

Kind Regards
Donovan Graham

donovan@platform7.com

UK +44 (0)208 1444283
SA +27 (0)82 7804636
SA +27 (0)21 5522338

**Comment by NV** [comment]
I don’t want to have it in the core but you can modify the Flying Focus for your website specifically. You can filter out links by adding the following code to [flying-focus.js:33](https://github.com/NV/flying-focus/blob/gh-pages/chrome/flying-focus.js#L33).

``` js
if (target.tagName == 'A') return;
```

**Comment by donovan-graham** [comment]
Great. Thanks, for the advice.

On Fri, Sep 20, 2013 at 3:48 PM, Nikita Vasilyev
notifications@github.comwrote:

> I don’t want to have it in the core but you can modify the Flying Focus
> for your website specifically. You can filter out links by adding the
> following code to flying-focus.js:33https://github.com/NV/flying-focus/blob/gh-pages/chrome/flying-focus.js#L33
> .
> 
> if (target.tagName == 'A') return;
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NV/flying-focus/issues/1#issuecomment-24811345
> .

## 

Kind Regards
Donovan Graham

donovan@platform7.com

UK +44 (0)208 1444283
SA +27 (0)82 7804636
SA +27 (0)21 5522338
