### ISSUE TITLE
Breaking in IE8

### ISSUE THREAD

**Issue by notslang** [NV/flying-focus#10]
![image](https://f.cloud.github.com/assets/1049204/2301082/7f1fc84e-a123-11e3-865f-8e68f43c24dc.png)

It's obviously not worth supporting IE8 since it doesn't have CSS3 transitions, but it should be noted that if this script is run in IE8, it will break when it hits `addEventListener`.

A good solution for sites that want to support IE8 would be for them to wrap their call to flying focus in a try/catch.

Or, if someone wants to get really fancy, adding feature detection for CSS3 transitions so that the script doesn't even run on browsers that don't support it would be awesome (assuming that all browsers that support CSS3 also support `addEventListener`).

**Comment by NV** [comment]
Thank you. Try it now.
