### ISSUE TITLE
(Chrome/OSX) mouse doesn't establish focus reference for radio/checkbox

### ISSUE THREAD

**Issue by lazylester** [NV/flying-focus#4]
Looking at the demo page http://n12v.com/focus-transition/

If I mouseclick on (e.g.) the radio buttons, they acquire focus. But if I then use tab to move focus, the focus moves to the first focusable element on the page.

This doesn't happen if I mouseclick in the text box. When I mouseclick in the text box, tab takes me to the next in the sequence (as I would expect).

Nice job, btw, it's a good feature. I like.

**Comment by NV** [comment]
It’s a Chrome (Blink) behavior, Flying Focus does not affect it.
