### ISSUE TITLE
bower install failing

### ISSUE THREAD

**Issue by Tjorriemorrie** [NV/flying-focus#5]
Can you add support for bower please?

**Comment by NV** [comment]
Do you want to use Flying Focus on your website?

standalone/flying-focus.js is not present in the repository, it has compiled from standalone/flying-focus.jspp.js. Since Bower basically links repos to its registry, I have to keep compiled version in the repository.

**Comment by Tjorriemorrie** [comment]
Oic, I wasn't aware of that. Would you consider having a `dist` and `src` structure then? Either way, thanks, this is great work.
